"""user_name

Revision ID: 366e560ea3ed
Revises: 8edbecba01ba
Create Date: 2022-12-11 18:35:23.920840

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = "366e560ea3ed"
down_revision = "8edbecba01ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(), nullable=True))
    op.execute(table("user", column("first_name")).update().values(first_name=""))
    op.alter_column("user", "first_name", nullable=False)

    op.add_column("user", sa.Column("last_name", sa.String(), nullable=True))
    op.execute(table("user", column("last_name")).update().values(last_name=""))
    op.alter_column("user", "last_name", nullable=False)

    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
